import 'package:flutter/material.dart';
import 'package:sid_base/sid_base.dart';

class DefaultColorSchemes {
  static const customDarkBackground = Color(0xff171717);

  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF496800),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFC5F272),
    onPrimaryContainer: Color(0xFF131F00),
    secondary: Color(0xFF596248),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFDDE6C6),
    onSecondaryContainer: Color(0xFF171E0A),
    tertiary: Color(0xFF396661),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFBCECE5),
    onTertiaryContainer: Color(0xFF00201D),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFEFCF4),
    onBackground: Color(0xFF1B1C17),
    surface: Color(0xFFFEFCF4),
    onSurface: Color(0xFF1B1C17),
    surfaceVariant: Color(0xFFE2E4D4),
    onSurfaceVariant: Color(0xFF45483D),
    outline: Color(0xFF75786B),
    onInverseSurface: Color(0xFFF2F1E9),
    inverseSurface: Color(0xFF30312C),
    inversePrimary: Color(0xFFAAD559),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF496800),
  );

  static const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFAAD559),
    onPrimary: Color(0xFF243600),
    primaryContainer: Color(0xFF364E00),
    onPrimaryContainer: Color(0xFFC5F272),
    secondary: Color(0xFFC1CAAB),
    onSecondary: Color(0xFF2C331D),
    secondaryContainer: Color(0xFF424A32),
    onSecondaryContainer: Color(0xFFDDE6C6),
    tertiary: Color(0xFFA0D0C9),
    onTertiary: Color(0xFF013733),
    tertiaryContainer: Color(0xFF1F4E49),
    onTertiaryContainer: Color(0xFFBCECE5),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: customDarkBackground,
    onBackground: Color(0xFFE4E3DB),
    surface: customDarkBackground,
    onSurface: Color(0xFFE4E3DB),
    surfaceVariant: Color(0xFF45483D),
    onSurfaceVariant: Color(0xFFC6C8B9),
    outline: Color(0xFF8F9284),
    onInverseSurface: Color(0xFF1B1C17),
    inverseSurface: Color(0xFFE4E3DB),
    inversePrimary: Color(0xFF496800),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFAAD559),
  );


  static ColorScheme get bwLightScheme => ColorScheme(
        brightness: Brightness.light,
        primary: Colors.black.withTone(40),
        onPrimary: Colors.black.withTone(100),
        primaryContainer: Colors.black.withTone(90),
        onPrimaryContainer: Colors.black.withTone(10),
        secondary: Colors.black.withTone(40),
        onSecondary: Colors.black.withTone(100),
        secondaryContainer: Colors.black.withTone(90),
        onSecondaryContainer: Colors.black.withTone(10),
        tertiary: Colors.black.withTone(40),
        onTertiary: Colors.black.withTone(100),
        tertiaryContainer: Colors.black.withTone(90),
        onTertiaryContainer: Colors.black.withTone(10),
        error: const Color(0xFFBA1A1A),
        errorContainer: const Color(0xFFFFDAD6),
        onError: const Color(0xFFFFFFFF),
        onErrorContainer: const Color(0xFF410002),
        background: Colors.black.withTone(100),
        onBackground: Colors.black.withTone(10),
        surface: Colors.black.withTone(100),
        onSurface: Colors.black.withTone(10),
        surfaceVariant: Colors.black.withTone(98),
        onSurfaceVariant: Colors.black.withTone(30),
        outline: Colors.black.withTone(50),
        onInverseSurface: Colors.black.withTone(95),
        inverseSurface: Colors.black.withTone(20),
        inversePrimary: Colors.black.withTone(80),
        shadow: const Color(0xFF000000),
        surfaceTint: Colors.black.withTone(40),
      );

  static ColorScheme get bwDarkScheme => ColorScheme(
        brightness: Brightness.dark,
        primary: Colors.black.withTone(80),
        onPrimary: Colors.black.withTone(20),
        primaryContainer: Colors.black.withTone(30),
        onPrimaryContainer: Colors.black.withTone(90),
        secondary: Colors.black.withTone(80),
        onSecondary: Colors.black.withTone(20),
        secondaryContainer: Colors.black.withTone(30),
        onSecondaryContainer: Colors.black.withTone(90),
        tertiary: Colors.black.withTone(80),
        onTertiary: Colors.black.withTone(20),
        tertiaryContainer: Colors.black.withTone(30),
        onTertiaryContainer: Colors.black.withTone(90),
        error: const Color(0xFFFFB4AB),
        errorContainer: const Color(0xFF93000A),
        onError: const Color(0xFF690005),
        onErrorContainer: const Color(0xFFFFDAD6),
        background: customDarkBackground,
        onBackground: Colors.black.withTone(90),
        surface: customDarkBackground,
        onSurface: Colors.black.withTone(90),
        surfaceVariant: Colors.black.withTone(8),
        onSurfaceVariant: Colors.black.withTone(80),
        outline: Colors.black.withTone(60),
        onInverseSurface: Colors.black.withTone(95),
        inverseSurface: Colors.black.withTone(80),
        inversePrimary: Colors.black.withTone(20),
        shadow: const Color(0xFF000000),
        surfaceTint: Colors.black.withTone(80),
      );
}
